### PR TITLE
Markdown readme.md

### PR DESCRIPTION
**Pull request by eudaldgr**
It's self-explanatory.

### CODE REVIEW

**Comment by raspbeguy** [comment]
Great idea. I would prefer the filename to be `README.md` rather than `readme.md`.

**Comment by raspbeguy** [comment]
What do you mean?

**Comment by eudaldgr** [comment]
Uncial is a majuscule script (written entirely in capital letters) commonly used from the 4th to 8th centuries AD by Latin and Greek scribes.

**Comment by eudaldgr** [comment]
It has been a long time already, to continue using.

**Comment by raspbeguy** [comment]
OK thanks for clarifying.
Maybe that sounds stupid, but there is a reason this filename is in capital letters. When doing a `ls` for instance, it's much easier to get the list of texts you should read first. `README`, but also `LICENSE`, `CONTRIBUTE`, `TODO`, etc.

**Comment by arkamar** [comment]
I just have found this article
https://medium.com/@NSomar/readme-md-history-and-components-a365aff07f10 as I
was curious about the origin of capital file name and here is the reason:
> The reason for the all caps name is that in ASCII systems capital letters
> comes before small ones. This would make README file sort before all other
> source code files, which makes it more prominent for the developer.

**Comment by eudaldgr** [comment]
I understand the reasons, but i think it's unnecessary, but it's done.

> we are like a primary primate, if it is bigger more attention.

**Comment by arkamar** [comment]
I personally don't care if it is upper or lower case. I have shared the quote just from curiosity point of view.

**Pull request merged**
