### PR TITLE
travis-ci

### PR DESCRIPTION
**Pull request by eudaldgr**
self-explanatory

### CODE REVIEW

**Review by arkamar — APPROVED** [review]
LGTM

**Comment by eudaldgr** [comment]
what `LGTM` means?

**Comment by arkamar** [comment]
looks good to me

**Comment by jmdugan** [comment]
added the app

https://travis-ci.com/organizations/btpd/repositories

not sure if there's any other setting or user adds on that site? lmk

new to using apps like this across sites for CI. seems like something is happening with builds in this thread already tho

**Comment by eudaldgr** [comment]
@jmdugan yeah i'm trying now to build for the different `evloop-methods` before merging.

**Comment by arkamar** [comment]
`kqueue` is BSD thing. Linux does not have it.

**Comment by eudaldgr** [comment]
i see now, i don't know anything about BSD.

**Pull request merged**
